name: stx_bloc_base
description: The package provides various generic implementations of blocs.
version: 0.6.2

homepage: https://github.com/SoftonixMobile/stx_bloc_base
documentation: https://github.com/SoftonixMobile/stx_bloc_base
repository: https://github.com/SoftonixMobile/stx_bloc_base

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  bloc: ^9.2.1
  equatable: ^3.0.0
  meta: ^1.19.0

dev_dependencies:
  test: ^1.32.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.5
  lints: ^6.1.0
